'use babel';

export const Atom = {
  GITKRAKEN_BISECT_TITLE: 'GitKraken Bisect',
  GITKRAKEN_BISECT_URI: 'atom://gitkraken-bisect'
};

export const Bisect = {
  commitState: {
    BAD: 'BAD',
    GOOD: 'GOOD',
    UNKNOWN: 'UNKNOWN'
  },
  status: {
    FINISHED_RANGE: 'FINISHED_RANGE',
    FINISHED_SINGLE: 'FINISHED_SINGLE',
    IS_BISECTING: 'IS_BISECTING',
    REACHED_MERGE_BASE: 'REACHED_MERGE_BASE',
    STEP: 'STEP'
  },
  walkDirection: {
    DOWN: 'DOWN',
    UP: 'UP'
  }
};

export const Git = {
  client: {
    MAX_CONNECT_RETRIES: 40, // 10 seconds
    WAIT_BETWEEN_CONNECT_RETRIES: 250,
  }
};

export const State = {
  INIT: 'INIT',
  COMMIT_LIST_LOADING: 'COMMIT_LIST_LOADING',
  COMMIT_LIST_SHOWN: 'COMMIT_LIST_SHOWN',
  COMMIT_1_SELECTED: 'COMMIT_1_SELECTED',
  COMMIT_2_SELECTED: 'COMMIT_2_SELECTED',
  BISECT_CHECKOUT_TRIGGERED: 'BISECT_CHECKOUT_TRIGGERED',
  BISECT_CLARIFY_COMMIT_SELECTION: 'BISECT_CLARIFY_COMMIT_SELECTION',
  BISECT_COMMIT_CHECKED_OUT: 'BISECT_COMMIT_CHECKED_OUT',
  BISECT_COMMIT_SELECTION_CLARIFIED: 'BISECT_COMMIT_SELECTION_CLARIFIED',
  BISECT_COMPLETED_RANGE: 'BISECT_COMPLETED_RANGE',
  BISECT_COMPLETED_SINGLE: 'BISECT_COMPLETED_SINGLE',
  BISECT_REACHED_MERGE_BASE: 'BISECT_REACHED_MERGE_BASE',
  BISECT_SHAS_CALCULATED: 'BISECT_SHAS_CALCULATED',
  BISECT_STARTED: 'BISECT_STARTED',
  GIT_INITIALIZED: 'GIT_INITIALIZED',
};
