'use babel';

export const Atom = {
  GIT_BISECT_TITLE: 'Git Bisect',
  GIT_BISECT_URI: 'atom://git-bisect'
};

export const Bisect = {
  commitState: {
    BAD: 'BAD',
    GOOD: 'GOOD',
    UNKNOWN: 'UNKNOWN'
  }
};

export const State = {
  INIT: 'INIT',
  COMMIT_LIST_LOADING: 'COMMIT_LIST_LOADING',
  COMMIT_LIST_SHOWN: 'COMMIT_LIST_SHOWN',
  COMMIT_1_SELECTED: 'COMMIT_1_SELECTED',
  COMMIT_2_SELECTED: 'COMMIT_2_SELECTED',
  BISECT_CHECKOUT_TRIGGERED: 'BISECT_CHECKOUT_TRIGGERED',
  BISECT_COMMIT_CHECKED_OUT: 'BISECT_COMMIT_CHECKED_OUT',
  BISECT_COMPLETED: 'BISECT_COMPLETED',
  GIT_INITIALIZED: 'GIT_INITIALIZED'
};
